import {
  IconArmchair,
  IconBabyCarriage,
  IconBallFootball,
  IconBasket,
  IconBike,
  IconBook,
  IconBooks,
  IconBriefcase,
  IconBulb,
  IconBuildingBank,
  IconBuildingStore,
  IconBus,
  IconCactus,
  IconCake,
  IconCalculator,
  IconCalendar,
  IconCamera,
  IconCar,
  IconCat,
  IconChartBar,
  IconChartPie,
  IconClock,
  IconClothesRack,
  IconCloud,
  IconCoffee,
  IconCoin,
  IconCrown,
  IconCurrencyDollar,
  IconCurrencyEuro,
  IconCurrencyPound,
  IconCurrencyYen,
  IconDeviceGamepad,
  IconDeviceLaptop,
  IconDeviceWatch,
  IconDog,
  IconDroplet,
  IconEye,
  IconFeather,
  IconFlower,
  IconFridge,
  IconGift,
  IconGlass,
  IconGlobe,
  IconHammer,
  IconHeart,
  IconHome,
  IconHospital,
  IconKeyboard,
  IconLamp,
  IconMail,
  IconMap,
  IconMessage,
  IconMicrophone,
  IconMusic,
  IconPalette,
  IconPaw,
  IconPencil,
  IconPhone,
  IconPlane,
  IconPlaneTilt,
  IconPlant,
  IconPlug,
  IconPool,
  IconPuzzle,
  IconReceipt,
  IconRocket,
  IconRun,
  IconScissors,
  IconShoppingCart,
  IconShovel,
  IconStar,
  IconStethoscope,
  IconSun,
  IconSwimming,
  IconTarget,
  IconTeapot,
  IconTent,
  IconTool,
  IconTrekking,
  IconTrophy,
  IconTruck,
  IconUmbrella,
  IconUser,
  IconUsers,
  IconVaccineBottle,
  IconWallet,
  IconWeight,
  IconWind,
  IconWorld,
  type TablerIcon,
} from "@tabler/icons-react";
import { ThemeIcon } from "@mantine/core";

interface BucketIconProps {
  name: string;
  size?: number;
  color?: string;
}

const ICON_MAP: Record<string, TablerIcon> = {
  wallet: IconWallet,
  home: IconHome,
  car: IconCar,
  "shopping-cart": IconShoppingCart,
  basket: IconBasket,
  receipt: IconReceipt,
  "building-bank": IconBuildingBank,
  "building-store": IconBuildingStore,
  coin: IconCoin,
  calculator: IconCalculator,
  "chart-bar": IconChartBar,
  "chart-pie": IconChartPie,
  target: IconTarget,
  briefcase: IconBriefcase,
  droplet: IconDroplet,
  coffee: IconCoffee,
  glass: IconGlass,
  cake: IconCake,
  gift: IconGift,
  heart: IconHeart,
  star: IconStar,
  crown: IconCrown,
  trophy: IconTrophy,
  rocket: IconRocket,
  plane: IconPlane,
  "plane-tilt": IconPlaneTilt,
  truck: IconTruck,
  bus: IconBus,
  bike: IconBike,
  run: IconRun,
  trekking: IconTrekking,
  swimming: IconSwimming,
  pool: IconPool,
  tent: IconTent,
  plant: IconPlant,
  flower: IconFlower,
  cactus: IconCactus,
  teapot: IconTeapot,
  lamp: IconLamp,
  bulb: IconBulb,
  tool: IconTool,
  hammer: IconHammer,
  shovel: IconShovel,
  scissors: IconScissors,
  pencil: IconPencil,
  book: IconBook,
  books: IconBooks,
  music: IconMusic,
  guitar: IconMusic,
  camera: IconCamera,
  phone: IconPhone,
  laptop: IconDeviceLaptop,
  keyboard: IconKeyboard,
  watch: IconDeviceWatch,
  "clothes-rack": IconClothesRack,
  armchair: IconArmchair,
  fridge: IconFridge,
  plug: IconPlug,
  hospital: IconHospital,
  vaccine: IconVaccineBottle,
  stethoscope: IconStethoscope,
  weight: IconWeight,
  "baby-carriage": IconBabyCarriage,
  dog: IconDog,
  cat: IconCat,
  paw: IconPaw,
  globe: IconGlobe,
  world: IconWorld,
  map: IconMap,
  cloud: IconCloud,
  sun: IconSun,
  wind: IconWind,
  umbrella: IconUmbrella,
  calendar: IconCalendar,
  clock: IconClock,
  mail: IconMail,
  message: IconMessage,
  user: IconUser,
  users: IconUsers,
  eye: IconEye,
  puzzle: IconPuzzle,
  gamepad: IconDeviceGamepad,
  football: IconBallFootball,
  microphone: IconMicrophone,
  palette: IconPalette,
  feather: IconFeather,
};

export function BucketIcon({ name, size = 18, color }: BucketIconProps) {
  const Icon = ICON_MAP[name] ?? IconWallet;
  return (
    <ThemeIcon variant="light" color={color ?? "teal"} size={size}>
      <Icon size={size * 0.7} />
    </ThemeIcon>
  );
}
