/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["api_urls_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login View */
        post: operations["api_views_auth_login_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout View */
        post: operations["api_views_auth_logout_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me View */
        get: operations["api_views_auth_me_view"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buckets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Buckets */
        get: operations["api_views_buckets_list_buckets"];
        put?: never;
        /** Create Bucket */
        post: operations["api_views_buckets_create_bucket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buckets/{bucket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bucket */
        get: operations["api_views_buckets_get_bucket"];
        /** Update Bucket */
        put: operations["api_views_buckets_update_bucket"];
        post?: never;
        /** Delete Bucket */
        delete: operations["api_views_buckets_delete_bucket"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buckets/{bucket_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Bucket */
        post: operations["api_views_buckets_reset_bucket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buckets/{bucket_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Share Bucket */
        post: operations["api_views_buckets_share_bucket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buckets/{bucket_id}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shares */
        get: operations["api_views_buckets_list_shares"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buckets/{bucket_id}/share/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Share */
        delete: operations["api_views_buckets_remove_share"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buckets/{bucket_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bucket Logs */
        get: operations["api_views_buckets_list_bucket_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buckets/{bucket_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["api_views_transactions_list_transactions"];
        put?: never;
        /** Create Transaction */
        post: operations["api_views_transactions_create_transaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Transactions View */
        get: operations["api_views_transactions_admin_transactions_view"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Transaction */
        put: operations["api_views_transactions_update_transaction"];
        post?: never;
        /** Soft Delete Transaction */
        delete: operations["api_views_transactions_soft_delete_transaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo Delete */
        post: operations["api_views_transactions_undo_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["api_views_insights_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly Trend */
        get: operations["api_views_insights_monthly_trend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["api_views_settings_get_settings"];
        /** Update Settings */
        put: operations["api_views_settings_update_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["api_views_users_list_users"];
        put?: never;
        /** Create User */
        post: operations["api_views_users_create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Get User */
        get: operations["api_views_users_get_user"];
        /** Update User */
        patch: operations["api_views_users_update_user"];
        /** Delete User */
        delete: operations["api_views_users_delete_user"];
        options?: never;
        head?: never;
        trace?: never;
    };
    "/api/admin/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Summary */
        get: operations["api_views_admin_admin_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthResponse */
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Last Login At */
            last_login_at: string | null;
            /** Login Count */
            login_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Error */
            error: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** BucketResponse */
        BucketResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Amount */
            amount: number;
            /** Spent */
            spent: number;
            /** Currency */
            currency: string;
            /** Color */
            color: string;
            /** Icon */
            icon: string;
            /** Distribute To Period */
            distribute_to_period: string;
            /** Owner Id */
            owner_id: number;
            /** Owner Name */
            owner_name: string;
            /** Shared */
            shared: boolean;
        };
        /** BucketCreate */
        BucketCreate: {
            /** Name */
            name: string;
            /** Amount */
            amount: number | string;
            /** Description */
            description?: string | null;
            /**
             * Currency
             * @default AUD
             */
            currency: string;
            /**
             * Color
             * @default #3B82F6
             */
            color: string;
            /**
             * Icon
             * @default wallet
             */
            icon: string;
            /**
             * Distribute To Period
             * @default monthly
             */
            distribute_to_period: string;
        };
        /** BucketUpdate */
        BucketUpdate: {
            /** Name */
            name?: string | null;
            /** Amount */
            amount?: number | string | null;
            /** Description */
            description?: string | null;
            /** Currency */
            currency?: string | null;
            /** Color */
            color?: string | null;
            /** Icon */
            icon?: string | null;
            /** Distribute To Period */
            distribute_to_period?: string | null;
        };
        /** BucketShareResponse */
        BucketShareResponse: {
            /** Id */
            id: number;
            /** Bucket Id */
            bucket_id: number;
            /** User Id */
            user_id: number;
            /** Permission */
            permission: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BucketShareCreate */
        BucketShareCreate: {
            /** User Id */
            user_id: number;
            /**
             * Permission
             * @default read
             */
            permission: string;
        };
        /** BucketLogResponse */
        BucketLogResponse: {
            /** Id */
            id: number;
            /** Action */
            action: string;
            /** Old Value */
            old_value: string | null;
            /** New Value */
            new_value: string | null;
            /** Reason */
            reason: string | null;
            /**
             * Performed At
             * Format: date-time
             */
            performed_at: string;
            /** Bucket Id */
            bucket_id: number;
        };
        /** TransactionResponse */
        TransactionResponse: {
            /** Id */
            id: number;
            /** Amount */
            amount: number;
            /** Notes */
            notes: string | null;
            /**
             * Spent At
             * Format: date-time
             */
            spent_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Bucket Id */
            bucket_id: number;
            /** Bucket Name */
            bucket_name: string | null;
            /** User Id */
            user_id: number;
            /** User Name */
            user_name: string | null;
        };
        /** TransactionCreate */
        TransactionCreate: {
            /** Bucket Id */
            bucket_id: number;
            /** Amount */
            amount: number | string;
            /** Notes */
            notes?: string | null;
            /**
             * Spent At
             * Format: date-time
             */
            spent_at: string;
        };
        /** TransactionUpdate */
        TransactionUpdate: {
            /** Amount */
            amount?: number | string | null;
            /** Notes */
            notes?: string | null;
            /** Spent At */
            spent_at?: string | null;
        };
        /** InsightSummary */
        InsightSummary: {
            /** Month */
            month: number;
            /** Year */
            year: number;
            /** Total Budget */
            total_budget: number;
            /** Total Spent */
            total_spent: number;
            /** Remaining */
            remaining: number;
        };
        /** MonthlyTrend */
        MonthlyTrend: {
            /** Month */
            month: number;
            /** Year */
            year: number;
            /** Budget */
            budget: number;
            /** Spent */
            spent: number;
            /** Remaining */
            remaining: number;
            /** Bucket Id */
            bucket_id: number;
        };
        /** UserSettingsResponse */
        UserSettingsResponse: {
            /** Base Currency */
            base_currency: string;
            /** Theme */
            theme: string;
        };
        /** UserSettingsUpdate */
        UserSettingsUpdate: {
            /** Base Currency */
            base_currency: string;
            /** Theme */
            theme?: string | null;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Name */
            name?: string | null;
            /** Password */
            password?: string | null;
            /** Is Staff */
            is_staff?: boolean | null;
        };
        /** AdminSummaryResponse */
        AdminSummaryResponse: {
            /** Total Users */
            total_users: number;
            /** Total Buckets */
            total_buckets: number;
            /** Total Transactions */
            total_transactions: number;
            /** Total Spent */
            total_spent: number;
            /** Recent Transactions */
            recent_transactions: components["schemas"]["TransactionResponse"][];
        };
        /** UserCreate */
        UserCreate: {
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_urls_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_auth_login_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    api_views_auth_logout_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_auth_me_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    api_views_buckets_list_buckets: {
        parameters: {
            query?: {
                user_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketResponse"][];
                };
            };
        };
    };
    api_views_buckets_create_bucket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BucketCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketResponse"];
                };
            };
        };
    };
    api_views_buckets_get_bucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketResponse"];
                };
            };
        };
    };
    api_views_buckets_update_bucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BucketUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketResponse"];
                };
            };
        };
    };
    api_views_buckets_delete_bucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_buckets_reset_bucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketResponse"];
                };
            };
        };
    };
    api_views_buckets_share_bucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BucketShareCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketShareResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    api_views_buckets_list_shares: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketShareResponse"][];
                };
            };
        };
    };
    api_views_buckets_remove_share: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: number;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_buckets_list_bucket_logs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketLogResponse"][];
                };
            };
        };
    };
    api_views_transactions_list_transactions: {
        parameters: {
            query?: {
                include_deleted?: boolean;
            };
            header?: never;
            path: {
                bucket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"][];
                };
            };
        };
    };
    api_views_transactions_create_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    api_views_transactions_admin_transactions_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"][];
                };
            };
        };
    };
    api_views_transactions_update_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
        };
    };
    api_views_transactions_soft_delete_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_transactions_undo_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    api_views_insights_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightSummary"][];
                };
            };
        };
    };
    api_views_insights_monthly_trend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyTrend"][];
                };
            };
        };
    };
    api_views_settings_get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsResponse"];
                };
            };
        };
    };
    api_views_settings_update_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsResponse"];
                };
            };
        };
    };
    api_views_users_list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    api_views_users_create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    api_views_users_get_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    api_views_users_update_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    api_views_users_delete_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    api_views_admin_admin_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSummaryResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
